version: '3'
services:
  product:
    image: vnrg/product:0.0.1
    ports:
      -"8080:8080"
    environment:
      - APP_PORT=8080
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          memory: 128m